### ISSUE TITLE
compilation error with "errx" and "err" under tests/ dir

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#111]
Hi,
Now I've got this compilation error on HP-UX 11i 11.31 with GCC.
<pre>
  CC       arc4randomforktest.o
arc4randomforktest.c: In function 'usage':
arc4randomforktest.c:72:2: error: expected expression before ')' token
*** Error exit code 1
</pre>
fallback for `errx` seems to cause this problem.
I can't point out what is wrong, now.
I'm investigating still.

**Comment by kinichiro** [comment]
I intentionally modify `errx` line like this, adding %d and argument.
`errx(1, "usage: arc4random-fork [-bp] %d",1);`
then, compilation succeeds.

And I noticed that commit https://github.com/libressl-portable/portable/commit/5d8a1cf7155130bd8101090d7e1d0c2f90d9b123 changes err.h under include/ .

**before** : include/err.h
<pre>
#define err(exitcode, format, args...) \
  errx(exitcode, format ": %s", ## args, strerror(errno))

#define errx(exitcode, format, args...) \
  do { warnx(format, ## args); exit(exitcode); } while (0)

#define warn(format, args...) \
  warnx(format ": %s", ## args, strerror(errno))

#define warnx(format, args...) \
  fprintf(stderr, format "\n", ## args)
</pre>

**after** : include/compat/err.h
<pre>
#define err(exitcode, format, ...) \
  errx(exitcode, format ": %s", __VA_ARGS__, strerror(errno))

#define errx(exitcode, format, ...) \
  do { warnx(format, __VA_ARGS__); exit(exitcode); } while (0)

#define warn(format, ...) \
  warnx(format ": %s", __VA_ARGS__, strerror(errno))

#define warnx(format, ...) \
  fprintf(stderr, format "\n", __VA_ARGS__)
</pre>

Could you add "##" before each "__VA_ARGS__", please ?

**Comment by busterb** [comment]
Thanks, I noticed this on the way home yesterday. Will fix right away.

**Comment by busterb** [comment]
Fixed in a9b16c2d66de5e4cda13c51b9a0c50964850a87c , thanks for the report.

**Comment by kinichiro** [comment]
Thanks, I could confirm this issue was fixed.

**Comment by bcook-r7** [comment]
I'm not happy with these macros, as they still throw visual studio for a loop. I'll probably replace them soon with regular variadic functions.
