### ISSUE TITLE
several "new" coverity findings

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#778]
coverity has updated their software, several "new" issues were detected.
just to track them (if they got lost in mailing list)

```
** CID 356045:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356045:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_cbc_cipher()
74     typedef struct {
75      BF_KEY ks;
76     } EVP_BF_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_BF_KEY,ctx)
79     
>>>     CID 356045:  Memory - corruptions  (OVERRUN)
>>>     Calling "BF_cbc_encrypt" with "in" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(bf, ks, BF, EVP_BF_KEY, NID_bf, 8, 16, 8, 64,
81         EVP_CIPH_VARIABLE_LENGTH, bf_init_key, NULL,
82         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
83     
84     static int
85     bf_init_key(EVP_CIPHER_CTX *ctx, const unsigned char *key,

** CID 356044:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 84 in camellia_192_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356044:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 84 in camellia_192_ofb_cipher()
78     IMPLEMENT_BLOCK_CIPHER(camellia_128, ks, Camellia, EVP_CAMELLIA_KEY,
79         NID_camellia_128, 16, 16, 16, 128,
80         0, camellia_init_key, NULL,
81         EVP_CIPHER_set_asn1_iv,
82         EVP_CIPHER_get_asn1_iv,
83         NULL)
>>>     CID 356044:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_ofb128_encrypt" with "out" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)

** CID 356043:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356043:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_cbc_cipher()
74     typedef struct {
75      CAST_KEY ks;
76     } EVP_CAST_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_CAST_KEY,ctx)
79     
>>>     CID 356043:  Memory - corruptions  (OVERRUN)
>>>     Calling "CAST_cbc_encrypt" with "out" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(cast5, ks, CAST, EVP_CAST_KEY,
81         NID_cast5, 8, CAST_KEY_LENGTH, 8, 64,
82         EVP_CIPH_VARIABLE_LENGTH, cast_init_key, NULL,
83         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
84     
85     static int

** CID 356042:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356042:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_cbc_cipher()
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)
>>>     CID 356042:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cbc_encrypt" with "in" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned.
90     IMPLEMENT_BLOCK_CIPHER(camellia_256, ks, Camellia, EVP_CAMELLIA_KEY,
91         NID_camellia_256, 16, 32, 16, 128,
92         0, camellia_init_key, NULL,
93         EVP_CIPHER_set_asn1_iv,
94         EVP_CIPHER_get_asn1_iv,
95         NULL)

** CID 356041:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356041:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_ofb_cipher()
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)
>>>     CID 356041:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_ofb128_encrypt" with "in" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
90     IMPLEMENT_BLOCK_CIPHER(camellia_256, ks, Camellia, EVP_CAMELLIA_KEY,
91         NID_camellia_256, 16, 32, 16, 128,
92         0, camellia_init_key, NULL,
93         EVP_CIPHER_set_asn1_iv,
94         EVP_CIPHER_get_asn1_iv,
95         NULL)

** CID 356040:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 78 in camellia_128_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356040:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 78 in camellia_128_ofb_cipher()
72      CAMELLIA_KEY ks;
73     } EVP_CAMELLIA_KEY;
74     
75     /* Attribute operation for Camellia */
76     #define data(ctx)        EVP_C_DATA(EVP_CAMELLIA_KEY,ctx)
77     
>>>     CID 356040:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_ofb128_encrypt" with "in" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
78     IMPLEMENT_BLOCK_CIPHER(camellia_128, ks, Camellia, EVP_CAMELLIA_KEY,
79         NID_camellia_128, 16, 16, 16, 128,
80         0, camellia_init_key, NULL,
81         EVP_CIPHER_set_asn1_iv,
82         EVP_CIPHER_get_asn1_iv,
83         NULL)

** CID 356039:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 78 in camellia_128_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356039:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 78 in camellia_128_cbc_cipher()
72      CAMELLIA_KEY ks;
73     } EVP_CAMELLIA_KEY;
74     
75     /* Attribute operation for Camellia */
76     #define data(ctx)        EVP_C_DATA(EVP_CAMELLIA_KEY,ctx)
77     
>>>     CID 356039:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cbc_encrypt" with "out" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned.
78     IMPLEMENT_BLOCK_CIPHER(camellia_128, ks, Camellia, EVP_CAMELLIA_KEY,
79         NID_camellia_128, 16, 16, 16, 128,
80         0, camellia_init_key, NULL,
81         EVP_CIPHER_set_asn1_iv,
82         EVP_CIPHER_get_asn1_iv,
83         NULL)

** CID 356038:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356038:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_cbc_cipher()
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)
>>>     CID 356038:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cbc_encrypt" with "out" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned.
90     IMPLEMENT_BLOCK_CIPHER(camellia_256, ks, Camellia, EVP_CAMELLIA_KEY,
91         NID_camellia_256, 16, 32, 16, 128,
92         0, camellia_init_key, NULL,
93         EVP_CIPHER_set_asn1_iv,
94         EVP_CIPHER_get_asn1_iv,
95         NULL)

** CID 356037:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 84 in camellia_192_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356037:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 84 in camellia_192_cbc_cipher()
78     IMPLEMENT_BLOCK_CIPHER(camellia_128, ks, Camellia, EVP_CAMELLIA_KEY,
79         NID_camellia_128, 16, 16, 16, 128,
80         0, camellia_init_key, NULL,
81         EVP_CIPHER_set_asn1_iv,
82         EVP_CIPHER_get_asn1_iv,
83         NULL)
>>>     CID 356037:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_cbc_encrypt" with "out" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned.
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)

** CID 356036:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356036:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_ofb_cipher()
74     typedef struct {
75      BF_KEY ks;
76     } EVP_BF_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_BF_KEY,ctx)
79     
>>>     CID 356036:  Memory - corruptions  (OVERRUN)
>>>     Calling "BF_ofb64_encrypt" with "out" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(bf, ks, BF, EVP_BF_KEY, NID_bf, 8, 16, 8, 64,
81         EVP_CIPH_VARIABLE_LENGTH, bf_init_key, NULL,
82         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
83     
84     static int
85     bf_init_key(EVP_CIPHER_CTX *ctx, const unsigned char *key,

** CID 356035:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/x509/x509_utl.c: 894 in valid_star()


________________________________________________________________________________________________________
*** CID 356035:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/x509/x509_utl.c: 894 in valid_star()
888                                     return NULL;
889                             state = LABEL_START;
890                             ++dots;
891                     } else if (p[i] == '-') {
892                             /* no domain/subdomain starts with '-' */
893                             if ((state & LABEL_START) != 0)
>>>     CID 356035:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "return NULL;".
894                                     return NULL;
895                             state |= LABEL_HYPHEN;
896                     } else
897                             return NULL;
898             }
899     

** CID 356034:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356034:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_cbc_cipher()
74     typedef struct {
75      CAST_KEY ks;
76     } EVP_CAST_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_CAST_KEY,ctx)
79     
>>>     CID 356034:  Memory - corruptions  (OVERRUN)
>>>     Calling "CAST_cbc_encrypt" with "in" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(cast5, ks, CAST, EVP_CAST_KEY,
81         NID_cast5, 8, CAST_KEY_LENGTH, 8, 64,
82         EVP_CIPH_VARIABLE_LENGTH, cast_init_key, NULL,
83         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
84     
85     static int

** CID 356033:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356033:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_camellia.c: 90 in camellia_256_ofb_cipher()
84     IMPLEMENT_BLOCK_CIPHER(camellia_192, ks, Camellia, EVP_CAMELLIA_KEY,
85         NID_camellia_192, 16, 24, 16, 128,
86         0, camellia_init_key, NULL,
87         EVP_CIPHER_set_asn1_iv,
88         EVP_CIPHER_get_asn1_iv,
89         NULL)
>>>     CID 356033:  Memory - corruptions  (OVERRUN)
>>>     Calling "Camellia_ofb128_encrypt" with "out" and "4611686018427387904UL" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
90     IMPLEMENT_BLOCK_CIPHER(camellia_256, ks, Camellia, EVP_CAMELLIA_KEY,
91         NID_camellia_256, 16, 32, 16, 128,
92         0, camellia_init_key, NULL,
93         EVP_CIPHER_set_asn1_iv,
94         EVP_CIPHER_get_asn1_iv,
95         NULL)

** CID 356032:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_rc2.c: 87 in rc2_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356032:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_rc2.c: 87 in rc2_ofb_cipher()
81      int key_bits;   /* effective key bits */
82      RC2_KEY ks;     /* key schedule */
83     } EVP_RC2_KEY;
84     
85     #define data(ctx)        ((EVP_RC2_KEY *)(ctx)->cipher_data)
86     
>>>     CID 356032:  Memory - corruptions  (OVERRUN)
>>>     Calling "RC2_ofb64_encrypt" with "in" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
87     IMPLEMENT_BLOCK_CIPHER(rc2, ks, RC2, EVP_RC2_KEY, NID_rc2,
88         8,
89         RC2_KEY_LENGTH, 8, 64,
90         EVP_CIPH_VARIABLE_LENGTH | EVP_CIPH_CTRL_INIT,
91         rc2_init_key, NULL,
92         rc2_set_asn1_type_and_iv, rc2_get_asn1_type_and_iv,

** CID 356031:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356031:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_cast.c: 80 in cast5_ofb_cipher()
74     typedef struct {
75      CAST_KEY ks;
76     } EVP_CAST_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_CAST_KEY,ctx)
79     
>>>     CID 356031:  Memory - corruptions  (OVERRUN)
>>>     Calling "CAST_ofb64_encrypt" with "out" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(cast5, ks, CAST, EVP_CAST_KEY,
81         NID_cast5, 8, CAST_KEY_LENGTH, 8, 64,
82         EVP_CIPH_VARIABLE_LENGTH, cast_init_key, NULL,
83         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
84     
85     static int

** CID 356030:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_rc2.c: 87 in rc2_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356030:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_rc2.c: 87 in rc2_cbc_cipher()
81      int key_bits;   /* effective key bits */
82      RC2_KEY ks;     /* key schedule */
83     } EVP_RC2_KEY;
84     
85     #define data(ctx)        ((EVP_RC2_KEY *)(ctx)->cipher_data)
86     
>>>     CID 356030:  Memory - corruptions  (OVERRUN)
>>>     Calling "RC2_cbc_encrypt" with "out" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
87     IMPLEMENT_BLOCK_CIPHER(rc2, ks, RC2, EVP_RC2_KEY, NID_rc2,
88         8,
89         RC2_KEY_LENGTH, 8, 64,
90         EVP_CIPH_VARIABLE_LENGTH | EVP_CIPH_CTRL_INIT,
91         rc2_init_key, NULL,
92         rc2_set_asn1_type_and_iv, rc2_get_asn1_type_and_iv,

** CID 356029:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_cbc_cipher()


________________________________________________________________________________________________________
*** CID 356029:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_cbc_cipher()
74     typedef struct {
75      BF_KEY ks;
76     } EVP_BF_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_BF_KEY,ctx)
79     
>>>     CID 356029:  Memory - corruptions  (OVERRUN)
>>>     Calling "BF_cbc_encrypt" with "out" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(bf, ks, BF, EVP_BF_KEY, NID_bf, 8, 16, 8, 64,
81         EVP_CIPH_VARIABLE_LENGTH, bf_init_key, NULL,
82         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
83     
84     static int
85     bf_init_key(EVP_CIPHER_CTX *ctx, const unsigned char *key,

** CID 356028:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_ofb_cipher()


________________________________________________________________________________________________________
*** CID 356028:  Memory - corruptions  (OVERRUN)
/home/runner/work/portable/portable/crypto/evp/e_bf.c: 80 in bf_ofb_cipher()
74     typedef struct {
75      BF_KEY ks;
76     } EVP_BF_KEY;
77     
78     #define data(ctx)        EVP_C_DATA(EVP_BF_KEY,ctx)
79     
>>>     CID 356028:  Memory - corruptions  (OVERRUN)
>>>     Calling "BF_ofb64_encrypt" with "in" and "4611686018427387904L" is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
80     IMPLEMENT_BLOCK_CIPHER(bf, ks, BF, EVP_BF_KEY, NID_bf, 8, 16, 8, 64,
81         EVP_CIPH_VARIABLE_LENGTH, bf_init_key, NULL,
82         EVP_CIPHER_set_asn1_iv, EVP_CIPHER_get_asn1_iv, NULL)
83     
84     static int
85     bf_init_key(EVP_CIPHER_CTX *ctx, const unsigned char *key,

** CID 356027:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/evp/e_aes.c: 1808 in aes_xts_init_key()


________________________________________________________________________________________________________
*** CID 356027:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/evp/e_aes.c: 1808 in aes_xts_init_key()
1802                            xctx->stream = enc ? bsaes_xts_encrypt :
1803                                bsaes_xts_decrypt;
1804                    else
1805     #endif
1806     #ifdef VPAES_CAPABLE
1807                    if (VPAES_CAPABLE) {
>>>     CID 356027:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "if (enc) {
  vpaes_set_encr...".
1808                            if (enc) {
1809                                    vpaes_set_encrypt_key(key, ctx->key_len * 4,
1810                                        &xctx->ks1);
1811                                    xctx->xts.block1 = (block128_f)vpaes_encrypt;
1812                            } else {
1813                                    vpaes_set_decrypt_key(key, ctx->key_len * 4,

** CID 356026:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/evp/e_aes.c: 1440 in aes_gcm_set_key()


________________________________________________________________________________________________________
*** CID 356026:  Control flow issues  (DEADCODE)
/home/runner/work/portable/portable/crypto/evp/e_aes.c: 1440 in aes_gcm_set_key()
1434                    CRYPTO_gcm128_init(gcm_ctx, aes_key, (block128_f)AES_encrypt);
1435                    return (ctr128_f)bsaes_ctr32_encrypt_blocks;
1436            } else
1437     #endif
1438     #ifdef VPAES_CAPABLE
1439            if (VPAES_CAPABLE) {
>>>     CID 356026:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "vpaes_set_encrypt_key(key, ...".
1440                    vpaes_set_encrypt_key(key, key_len * 8, aes_key);
1441                    CRYPTO_gcm128_init(gcm_ctx, aes_key, (block128_f)vpaes_encrypt);
1442                    return NULL;
1443            } else
1444     #endif
1445                    (void)0; /* terminate potentially open 'else' */
```

**Comment by 4a6f656c** [comment]
Thanks for the report - the issue is hidden deep under layers of macros. I've finally tracked the cause down and will commit some fixes in the near future.

**Comment by 4a6f656c** [comment]
I believe these should be addressed in primary repository - I'll wait for Coverity to confirm after the next sync has occurred.

**Comment by chipitsine** [comment]
coverity thinks issues are still there (i'll provide detailed traces from coverity in this issue)

![image](https://user-images.githubusercontent.com/2217296/189592574-dcab9219-e244-420c-891c-8e4c59c81f56.png)

**Comment by chipitsine** [comment]
CID 356045 long report

```
86static int
 87bf_cbc_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl)
 88{
   	1. Condition inl > 9223372036854775807L, taking false branch.
 89        if (inl > LONG_MAX)
 90                return 0;
 91
   	2. Condition inl >= (4611686018427387904UL /* (size_t)1 << sizeof (long) * 8 - 2 */), taking true branch.
 92        while (inl >= EVP_MAXCHUNK) {
     	CID 356029: Out-of-bounds access (OVERRUN) [[select issue](https://scan8.scan.coverity.com/defectInstanceId=12348146&fileInstanceId=61556823&mergedDefectId=356029)]
   	
CID 356045 (#1 of 1): Out-of-bounds access (OVERRUN)
3. overrun-buffer-arg: Calling BF_cbc_encrypt with in and 4611686018427387904L is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
 93                BF_cbc_encrypt(in, out, (long)EVP_MAXCHUNK, &((EVP_BF_KEY *)ctx->cipher_data)->ks, ctx->iv, ctx->encrypt);
 94                inl -= EVP_MAXCHUNK;
 95                in += EVP_MAXCHUNK;
 96                out += EVP_MAXCHUNK;
 97        }
```

CID 356044 long report

```
static int
304camellia_192_ofb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl)
305{
   	1. Condition inl >= (4611686018427387904UL /* (size_t)1 << sizeof (long) * 8 - 2 */), taking true branch.
306        while (inl >= EVP_MAXCHUNK) {
     	CID 356021: Out-of-bounds access (OVERRUN) [[select issue](https://scan8.scan.coverity.com/defectInstanceId=12348089&fileInstanceId=61556824&mergedDefectId=356021)]
   	
CID 356044 (#1 of 1): Out-of-bounds access (OVERRUN)
2. overrun-buffer-arg: Calling Camellia_ofb128_encrypt with out and 4611686018427387904UL is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
307                Camellia_ofb128_encrypt(in, out, EVP_MAXCHUNK, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, &ctx->num);
308                inl -= EVP_MAXCHUNK;
309                in += EVP_MAXCHUNK;
310                out += EVP_MAXCHUNK;
311        }
```

CID 356043 long report

```
86static int
 87cast5_cbc_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl)
 88{
   	1. Condition inl > 9223372036854775807L, taking false branch.
 89        if (inl > LONG_MAX)
 90                return 0;
 91
   	2. Condition inl >= (4611686018427387904UL /* (size_t)1 << sizeof (long) * 8 - 2 */), taking true branch.
 92        while (inl >= EVP_MAXCHUNK) {
     	CID 356034: Out-of-bounds access (OVERRUN) [[select issue](https://scan8.scan.coverity.com/defectInstanceId=12348104&fileInstanceId=61556825&mergedDefectId=356034)]
   	
CID 356043 (#1 of 1): Out-of-bounds access (OVERRUN)
3. overrun-buffer-arg: Calling CAST_cbc_encrypt with out and 4611686018427387904L is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned. [Note: The source code implementation of the function has been overridden by a builtin model.]
 93                CAST_cbc_encrypt(in, out, (long)EVP_MAXCHUNK, &((EVP_CAST_KEY *)ctx->cipher_data)->ks, ctx->iv, ctx->encrypt);
 94                inl -= EVP_MAXCHUNK;
 95                in += EVP_MAXCHUNK;
 96                out += EVP_MAXCHUNK;
 97        }
```

CID 356042 long report

```
407static int
408camellia_256_cbc_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl)
409{
   	1. Condition inl >= (4611686018427387904UL /* (size_t)1 << sizeof (long) * 8 - 2 */), taking true branch.
410        while (inl >= EVP_MAXCHUNK) {
     	CID 356038: Out-of-bounds access (OVERRUN) [[select issue](https://scan8.scan.coverity.com/defectInstanceId=12348087&fileInstanceId=61556824&mergedDefectId=356038)]
   	
CID 356042 (#1 of 1): Out-of-bounds access (OVERRUN)
2. overrun-buffer-arg: Calling Camellia_cbc_encrypt with in and 4611686018427387904UL is suspicious because of the very large index, 4611686018427387904. The index may be due to a negative parameter being interpreted as unsigned.
411                Camellia_cbc_encrypt(in, out, EVP_MAXCHUNK, &((EVP_CAMELLIA_KEY *)ctx->cipher_data)->ks, ctx->iv, ctx->encrypt);
412                inl -= EVP_MAXCHUNK;
413                in += EVP_MAXCHUNK;
414                out += EVP_MAXCHUNK;
415        }
```

**Comment by 4a6f656c** [comment]
@chipitsine - thanks, these are essentially false positives (at least in a real world sense), however I've since landed a better fix that should hopefully make Coverity happier.

**Comment by chipitsine** [comment]
issues were dismissed
